### ISSUE TITLE
Bottom contact cards animated

### ISSUE THREAD

**Issue by sinarhen** [rostiksqx/astro-coffee#3]
![image](https://github.com/rostiksqx/Astro-Blog/assets/105736826/f88197bf-33b3-4c90-a87c-5fb4007cd33a)

We have here three cards which are currently static and doesnt enhance User experience. I think we should do something cool on hover

**Comment by rostiksqx** [comment]
![image](https://github.com/rostiksqx/astro-coffee/assets/145684026/ce5d48bd-438d-458a-9ba2-9258688fcc4c)
done, cursor pointer and hover effect
