### ISSUE TITLE
Dynamic products

### ISSUE THREAD

**Issue by sinarhen** [rostiksqx/astro-coffee#4]
![image](https://github.com/rostiksqx/Astro-Blog/assets/105736826/87ae934b-5405-409f-8124-1a6d4ae30a93)

we should select 3 latest products from our store and display it on the landing. Provide an ability to make it dynamically with keystatic.

**Comment by rostiksqx** [comment]
![image](https://github.com/rostiksqx/astro-coffee/assets/145684026/b5b64767-0c9e-4c58-a19e-5506ea708784)
![image](https://github.com/rostiksqx/astro-coffee/assets/145684026/3515c6a2-fcc3-4750-9e79-d35708070d95)
Done
